### ISSUE TITLE
Build Error: Ref {HEAD} can not be resolved

### ISSUE THREAD

**Issue by tabalinas** [pubref/rules_node#15]
Hi,

Added `rules_node` definition to WORKSPACE as described in docs:

```py
git_repository(
    name = "org_pubref_rules_node",
    remote = "https://github.com/pubref/rules_node.git",
    commit = "{HEAD}",
)

load("@org_pubref_rules_node//node:rules.bzl", "node_repositories")

node_repositories()
```

When I build my package I get the following error:

`ERROR: error loading package '': Encountered error while reading extension file 'node/rules.bzl': no such package '@org_pubref_rules_node//node': Invalid branch, tag, or commit: Ref {HEAD} can not be resolved.`

Any help is highly appreciated.

I'm new to Bazel, probably, missing something obvious.

**Comment by tabalinas** [comment]
Using `tag = "v0.3.3"` instead of `commit` helped:

```
git_repository(
    name = "org_pubref_rules_node",
    remote = "https://github.com/pubref/rules_node.git",
    tag = "v0.3.3",
)
```

Still wondering why it doesn't work with `commit = "{HEAD}"`. Or docs should be updated?

**Comment by pcj** [comment]
Right, `{HEAD}` is not a special token, I'll update the docs to make it more explicit to substitute the head commit.  You can do:

```
git_repository(
    name = "org_pubref_rules_node",
    remote = "https://github.com/pubref/rules_node.git",
    commit = "494eafce2ff7df04047c28e39d956e4e788c5dfe",
)
```

**Comment by tabalinas** [comment]
I suspected this, thank you!
