### ISSUE TITLE
Bazel 0.5.3 seems to be unsupported

### ISSUE THREAD

**Issue by ittaiz** [pubref/rules_node#27]
Hi,
When I run `bazel test --spawn_strategy=standalone //...` I get the an error saying `mkdir -p vate/var/tmp/... failed`. 
For some reason on 0.5.3 (or somewhere after 0.4.4) the `/pri` prefix is dropped.

**Comment by pcj** [comment]
Hi @ittaiz I'm going to close this as 0.5.3 is on the travis matrix and somewhat out of date.  Pls re-open if needed.
