### ISSUE TITLE
Changing node_repositories version doesn't cause a re-build

### ISSUE THREAD

**Issue by ittaiz** [pubref/rules_node#28]
Hi,
I cloned the repo, built it and then tried fiddling with a different node version (6.9.0) but all targets were cached already.
Only after I ran `bazel clean --expunge` and built it again then I saw the 6.9.0 version being downloaded and used.
I think this might be because the repository rule is a macro which does the download outside of the implementation function of the repository rule itself.
Example of the change:
```
node_repositories(
    version="6.9.0",
    linux_sha256="a9aafa2499097b315e1554b882923a6e2f9c446d24eaea53630f0fdbe075b226",
    darwin_sha256="fd0f58487cd72d78e857bfc24061cfe77353e1571a17182b4e38273782648edf"
)
```

**Comment by pcj** [comment]
I think this is no longer an issue with the current repository architecture.  Pls re-open if remains an issue.
