### ISSUE TITLE
Jasmine support

### ISSUE THREAD

**Issue by ittaiz** [pubref/rules_node#29]
Hi,
I've fiddled around with the rules and saw that one can piggy back on top of `mocha_test` to get `jasmine_test`running.
It was simply a matter of replacing mocha with jasmine like so:
```
mocha_test(
    name = "jasmine_basic_test",
    main = "jasmine.test.spec.js",
    size = "small",
    mocha = "@npm_jasmine//:bin/jasmine",
    mocha_modules = "@npm_jasmine//:modules"
)
```
Are you interested in having this as a first class citizen?

**Comment by pcj** [comment]
This is a pretty cool result.  The mocha test rule has changed a bit since this comment so I am going to close this, but I think it would be a worthwhile addition to at least document in the README.
