### ISSUE TITLE
Bazel incompatible changes

### ISSUE THREAD

**Issue by laurentlb** [pubref/rules_node#75]
I had a quick look at the file (https://github.com/pubref/rules_node/blob/master/node/internal/yarn_modules.bzl), and I saw some deprecated constructs.

For example, `single_file = True` should be `allow_single_file = True`.
I recommend running `buildifier --lint=fix` (https://github.com/bazelbuild/buildtools) to fix some of the issues. For other recommendations, see also: https://groups.google.com/d/msg/bazel-dev/g4tYsUH46Gg/JhgAdwZ8AwAJ

Let me know if you need any help

**Comment by pcj** [comment]
Fixed by #81
